W-15854291: Separate file commons (#426)
* Remove file common dependency from source and test

* Remove file common from test scope

* Add privileged export

* Fixed File_Until and File_Since attribute

* Fixed failures due to different arguments

* Ignoring Failing Java tests

* Added javax.activation dependency

* Updated munit.version

* Formatting

* Upgraded min-version

* Added the MUnits for corresponding Java tests

* Additional Munit tests

* Read-write duplicate Test Case removed

* Create directory with special name test fix

* To-do: removed the OS assumption

* To-do: ignored test case fixed

* To-do: Remove redundant 'name' attribute

* Fixed Unnecessary Stubbing Exception

* W-16004666: Ftp list operation change to return file path rather than the file content.

* W-16004666: Munit to list all files and validate that if it return file path rather than the file content.

* W-16004666: Updated java doc for list operation to return file path rather than the file content.

* Update CODEOWNERS

* Remove nexus team entry from CODEOWNERS file

* Update CODEOWNERS

* W-15854291: Versions update based on renovate bot PRs as below-
org.mule.module:mule-java-module to v1.2.13
io.fabric8:docker-maven-plugin to v0.44.0
org.apache.commons:commons-lang3 to v3.14.0
com.mycila:license-maven-plugin to v4.5
org.codehaus.mojo:build-helper-maven-plugin to v3.6.0
commons-net:commons-net to v3.9.0
slf4j monorepo to v2.0.13
commons-io:commons-io to v2.16.1
munit.version to v3.2.1

* W-15854291: For list operation, made changes to not read the file content anymore underneath it and return the filepath in response rather than the content

* W-16280695: Removed the params timeBetweenSizeCheck and timeBetweenSizeCheckUnit from the input and it's corresponding usage since we'll not read the file content anymore.

* W-16280695: Moved constant file to internal package and removed mule runtime properties from pom since it's already included as part of a parent module pom

* W-16359329: Incorporating review comments by refactoring the code moved to ftp connector after eliminating dependency of mule-file-commons

* W-16359329: Fixed ftp-write-test-case.xml test case

* W-16359329: Removed the deprecated methods for read and write operations.

* W-16359329: Added javadoc to FtpFileAttributes as per the review comments.

* W-15854291: Refactored code to collapse hierarchy of FileSystem, AbstractFileSystem, AbstractExternalFileSystem, ExternalFileSystem and FtpFileSystem to  FileSystem and FtpFileSystem only.

* W-15854291: Refactored code to collapse following hierarchy:
1. AbstractFileCommand, ExternalFileCommand, FileCommand - FtpCommand
2. FileSystemProvider and FtpAbstractConnectionProvider -  FtpConnectionProvider

* W-15854291: Refactored code to collapse following hierarchy:
1. AbstractFileInputStreamSupplier and AbstractConnectedFileInputStreamSupplier - FtpFileInputStreamSupplier
2. AbstractPostActionGroup -  PostActionGroup
3. AbstractFtpCopyDelegate - FtpCopyDelegate

* W-15854291: Refactored code to collapse following hierarchy:
BaseFileSystemOperations - FtpOperations

* W-15854291: Incorporated review comments:
1. Make all the methods private which are used within that class
2. Remove implementing ConnectionProvider from FtpConnectionProvider
3. Changed default methods in FileSystem
4. Added descriptive javadoc to methods like getListCommand and similar

* W-15854291: Incorporated review comments:
keeping methods signature as same in api layer

* W-15854291: Incorporated review comments - removed lock(path) hierarchy from FileSystem and added null check for getTotalResults

* W-15854291: Removed this TODO since it's valid for sftp and not for ftp connector

* W-15854291: As discussed changed page list size

* W-15854291: Incorporated review comments-
1. FtpDirectoryListener : change directory source to InputStream which was there previously
2. FtpFileAttributes : keeping param path and name as consistent and its corresponding changes

* W-15854291: Fixed munits, renamed filename to name

* W-15854291: Changed FtpDirectoryListener approach to convert the path from the list operation into the InputStream before processFile method call

* W-15854291: Changed FtpDirectoryListener approach to make read call after the list operation to get the InputStream before processFile method call

* W-15854291: Keeping the FileSystemProvider, FtpAbstractConnectionProvider and FtpConnectionProvider hierarchy same as previous since its required by FTPS Connector.

* W-15854291: Fixed ignored junits:
1. Downgraded core module parent to previous one.
2. Done refactoring by moving few files from internal to api package since it was not getting loaded by junit and was throwing NoClassDefFoundError.

* W-15854291: Fixed Ftp list test case

* W-15854291: Core parent version upgrade to 1.3.2 and corresponding junits fix

---------

Co-authored-by: Dipesh Kumar Dutta <dipeshkumar.dutta@salesforce.com>
Co-authored-by: chirag868 <chirag.agarwal@salesforce.com>
Co-authored-by: dipeshkumardutta-sfemu <160039229+dipeshkumardutta-sfemu@users.noreply.github.com>
Co-authored-by: chirag868 <159425573+chirag868@users.noreply.github.com>